jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      if: ${{ matrix.version == '8' }}
      name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        distribution: adopt
        java-package: jdk+fx
        java-version: '1.8'
    - continue-on-error: true
      if: ${{ matrix.version == '8' }}
      name: Add openjfx FOR JDK8
      run: sudo apt-get install openjfx
    - continue-on-error: true
      if: ${{ matrix.version == '8' }}
      name: Build FOR JDK8
      run: mvn assembly:assembly -f pom.xml
    - continue-on-error: true
      if: ${{ matrix.version == '11' }}
      name: Set up JDK 11 ${{ matrix.version }}
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-package: jdk
        java-version: '11'
    - continue-on-error: true
      if: ${{ matrix.version == '11' }}
      name: Build FOR JDK11
      run: mvn assembly:assembly -f pom-jdk11.xml
    strategy:
      fail-fast: true
      matrix:
        version:
        - 8
        - 11
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
