jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      if: ${{ matrix.version == '8' }}
      name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        distribution: adopt
        java-package: jdk+fx
        java-version: '1.8'
    - continue-on-error: true
      if: ${{ matrix.version == '8' }}
      name: Build fofa_viewer For JDK 8
      run: mvn -DskipTests assembly:assembly -f pom.xml
    - continue-on-error: true
      if: ${{ matrix.version == '11' }}
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-package: jdk
        java-version: '11'
    - continue-on-error: true
      if: ${{ matrix.version == '11' }}
      name: Build FOR JDK11
      run: mvn assembly:assembly -f pom-jdk11.xml
    - continue-on-error: true
      name: Copy out packages fofa_viewer ${{ matrix.version }}
      run: 'cp target/fofaviewer-jar-with-dependencies.jar .

        mv fofaviewer-jar-with-dependencies.jar fofaviewer.jar

        mv config-example.properties config.properties

        zip ${{ matrix.version }}.zip fofaviewer.jar config.properties

        '
    - continue-on-error: true
      name: upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.version }}.zip
        path: ${{ matrix.version }}.zip
    strategy:
      fail-fast: true
      matrix:
        version:
        - 8
        - 11
  release:
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: github_release
      name: Build Changelog
      uses: mikepenz/release-changelog-builder-action@main
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      id: get_version
      name: Get version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: create_release
      name: Create Release
      uses: actions/create-release@v1
      with:
        body: ${{steps.github_release.outputs.changelog}}
        draft: false
        prerelease: false
        release_name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
    - continue-on-error: true
      name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: 8.zip
        path: ./
    - continue-on-error: true
      name: Download artifacts11
      uses: actions/download-artifact@v2
      with:
        name: 11.zip
        path: ./
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: upload-release-fofa_viewer-JDK8
      name: Upload fofa_viewer JDK8 Version
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: application/gzip
        asset_name: FofaViewer_${{ steps.get_version.outputs.VERSION }}_JDK8.zip
        asset_path: 8.zip
        upload_url: ${{ steps.create_release.outputs.upload_url }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: upload-release-fofa_viewer11
      name: Upload fofa_viewer
      uses: actions/upload-release-asset@v1
      with:
        asset_content_type: application/gzip
        asset_name: FofaViewer_${{ steps.get_version.outputs.VERSION }}.zip
        asset_path: 11.zip
        upload_url: ${{ steps.create_release.outputs.upload_url }}
name: Build fofa_viewer release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
